# Generated by Django 4.2.3 on 2023-07-27 03:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='from_address',
            field=models.UUIDField(default=uuid.UUID('2d0ddc79-1942-46cc-9a64-b4cd5d5bb2d7')),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_address',
            field=models.UUIDField(default=uuid.UUID('2d0ddc79-1942-46cc-9a64-b4cd5d5bb2d7')),
        ),
    ]
