# Generated by Django 4.2.3 on 2023-07-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_transaction_from_address_transaction_to_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='from_address',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_address',
            field=models.UUIDField(),
        ),
    ]
