# Generated by Django 4.2.3 on 2023-07-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_transaction_from_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet_amount',
            field=models.FloatField(default=5000, verbose_name='Сумма на счету'),
        ),
    ]
